//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WpfAppDocFxWLoggingZipTestProject1
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TestLogDir")]
        public string CurrentUnitTestLogDirValue
        {
            get
            {
                return ((string)(this["CurrentUnitTestLogDirValue"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("testhost")]
        public string ExpectedAppNameValue
        {
            get
            {
                return ((string)(this["ExpectedAppNameValue"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("urn:schemas-microsoft-com:unattend")]
        public string urnSchemasMicrosoftComUnattend
        {
            get
            {
                return ((string)(this["urnSchemasMicrosoftComUnattend"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://schemas.microsoft.com/WMIConfig/2002/State")]
        public string httpSchemasMicrosoftComWMIConfig2002State
        {
            get
            {
                return ((string)(this["httpSchemasMicrosoftComWMIConfig2002State"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WPFTestProjectLog")]
        public string UnitTestLogFileName
        {
            get
            {
                return ((string)(this["UnitTestLogFileName"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public global::System.Globalization.CultureInfo cultures
        {
            get
            {
                return ((global::System.Globalization.CultureInfo)(this["cultures"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExpectedBoolValueNameValue
        {
            get
            {
                return ((bool)(this["ExpectedBoolValueNameValue"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ExpectedIntValueNameValue
        {
            get
            {
                return ((int)(this["ExpectedIntValueNameValue"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WPFAppWithDocFxLoggingAndZip2.FileLogger")]
        public string ExpectedILoggerValue
        {
            get
            {
                return ((string)(this["ExpectedILoggerValue"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft.Extensions.Logging.LoggerFactory")]
        public string ExpectedFactoryValue
        {
            get
            {
                return ((string)(this["ExpectedFactoryValue"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WPFTestProjectLogFileTest")]
        public string UnitTestLogFileNameTest
        {
            get
            {
                return ((string)(this["UnitTestLogFileNameTest"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UnitTestZipFile.zip")]
        public string UnitTestZipFile
        {
            get
            {
                return ((string)(this["UnitTestZipFile"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Readme.txt")]
        public string UnitTestZipFileNameToCreate
        {
            get
            {
                return ((string)(this["UnitTestZipFileNameToCreate"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This Readme.txt file is created during the Zip Process and added to the zip file." +
            ",Information about this package.,Line 2.,Line 3.,Line 4.,=======================" +
            "=")]
        public string UnitTestZipFileLinesToAddToNewFile
        {
            get
            {
                return ((string)(this["UnitTestZipFileLinesToAddToNewFile"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Optimal")]
        public global::System.IO.Compression.CompressionLevel UnitTestZipFileCompressionLevel
        {
            get
            {
                return ((global::System.IO.Compression.CompressionLevel)(this["UnitTestZipFileCompressionLevel"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Readme.txt")]
        public string UnitTestZipFileNameToDelete
        {
            get
            {
                return ((string)(this["UnitTestZipFileNameToDelete"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NewReadme.txt")]
        public string UnitTestZipFileToAddFullName
        {
            get
            {
                return ((string)(this["UnitTestZipFileToAddFullName"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SampleDirectory")]
        public string UnitTestZipFileFromDirectory
        {
            get
            {
                return ((string)(this["UnitTestZipFileFromDirectory"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hello.docx")]
        public string UnitTestZipFileFromDirectoryFileExist
        {
            get
            {
                return ((string)(this["UnitTestZipFileFromDirectoryFileExist"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LogMessage Returned")]
        public string UnitTestLogMessage
        {
            get
            {
                return ((string)(this["UnitTestLogMessage"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LogErrorMessage Returned")]
        public string UnitTestLogErrorMessage
        {
            get
            {
                return ((string)(this["UnitTestLogErrorMessage"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LogInformationMessage Returned")]
        public string UnitTestLogInformationMessage
        {
            get
            {
                return ((string)(this["UnitTestLogInformationMessage"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LogTraceMessage Returned")]
        public string UnitTestLogTraceMessage
        {
            get
            {
                return ((string)(this["UnitTestLogTraceMessage"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LogDebugMessage Returned")]
        public string UnitTestLogDebugMessage
        {
            get
            {
                return ((string)(this["UnitTestLogDebugMessage"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LogWarningMessage Returned")]
        public string UnitTestLogWarningMessage
        {
            get
            {
                return ((string)(this["UnitTestLogWarningMessage"]));
            }
        }
    }
}
